name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker run -e CI=true $DOCKER_USERNAME/react-test npm test

      - name: Prod build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        working-directory: ./
        run: |
          docker build -t $DOCKER_USERNAME/multi-client:latest -f ./client/Dockerfile ./client
          docker build -t $DOCKER_USERNAME/multi-server:latest -f ./server/Dockerfile ./server
          docker build -t $DOCKER_USERNAME/multi-worker:latest -f ./worker/Dockerfile ./worker
          docker build -t $DOCKER_USERNAME/multi-nginx:latest -f ./nginx/Dockerfile ./nginx

      - name: Deploy to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push $DOCKER_USERNAME/multi-client:latest
          docker push $DOCKER_USERNAME/multi-server:latest
          docker push $DOCKER_USERNAME/multi-worker:latest
          docker push $DOCKER_USERNAME/multi-nginx:latest
